language: python
python:
- '3.8'
sudo: required
before install:
- sudo apt-get -y install hmmer
install:
- pip install .
before_script:
- cd $TRAVIS_BUILD_DIR
# - mkdir $TRAVIS_BUILD_DIR/annotation_tools
script:
- wget https://github.com/BIONF/data4travis/raw/main/dtu/signalp-4.1g.Linux.tar.gz &> /dev/null
- wget https://github.com/BIONF/data4travis/raw/main/dtu/tmhmm-2.0c.Linux.tar.gz &> /dev/null
- wget https://applbio.biologie.uni-frankfurt.de/download/hamstr_qfo/annotation_FAS2020d.tar.gz &> /dev/null
#- mv annotation_FAS2020d.tar.gz $TRAVIS_BUILD_DIR/annotation_tools
- setupFAS -t $TRAVIS_BUILD_DIR -d $TRAVIS_BUILD_DIR
- less annoTools.txt | grep -v "COILS2" > annoTools.txt.mod
- mv annoTools.txt.mod annoTools.txt
- hmmscan -E 0.01 --domE 0.1 --noali --cpu 1 Pfam/Pfam-hmms/Pfam-A.hmm "greedyFAS/annoFAS/test_annofas.fa"
- annoFAS -i test_annofas.fa -o test_output
- ls
- ls $TRAVIS_BUILD_DIR/test_output
# - python3 greedyFAS/calcFAS.py -h
# - python3 greedyFAS/fdogFAS.py -h
# - python3 greedyFAS/complexityFAS.py -h
# - python3 greedyFAS/annoFAS/annoFAS.py -h
# - python3 greedyFAS/annoFAS/annoParserFAS.py -h
# - python3 greedyFAS/setupFAS.py -h
# - python3 greedyFAS/domainFAS.py -h
branches:
  only:
    - master
    - /^v.*$/
deploy:
  provider: pypi
  username: __token__
  password:
    secure: J3YOdiKbjHJ5hgoqN/qk3oPRcq69kk7HL0KaNGtAahoKULvvBMydHFq04sbqAZj5Ixx+lROVIPNRLTcrC2643XUjk2nTyFk6987HIsAcID7+QTaxYVGrlb5lSngGT4AakjYLxBPpo5aKmAsMjF78a9ZIFx0nPVKOBQdGJTz4H+aV06AFywWXUurcfn8xG3V2HPfKA6yZD/WAm2BbV0DqLTCXK/DKl9fV8m06j/qYnmGNOZA2U0+gwnmWgqwIOP7jMT2LOIYxKht3YRuSI8Gmug7eYzyqX4rs0viK9esnEiwZxHld1HYEHeTSW0QjDjSdfRUwCQpbn17N/MFlezSg3c/Rl8c+j8//5hz4nK2mmgSDxEe4hPR+y1hLTB/UgVDqTAVBdEDlfnSQh+Ki4X8DslgQwcg7wuD+acC71oKTEVIGUxTlfcOUjjmFBaSu8ROwoNcHbrwrwoxWivCRv5na9YEqeKYNFAst9l8n9xQ/E7nPODV2Ol90xERf8BQ3BF3G9bgAJYr2oEZEIKguXzJbI4aggut2ca7RQJ22wSbSlsaHINXm30aIkZuddb7ZjfVIIhr5B6hjEtayfo5VmjfiPZwhSIcqK74bPlCxqZ4EW5ck3pEcuTWBehZm6n2VrsY8UvQHb8r7zydJ5DVx3daCPNV8Zx4OlF5O/+wbGwAKQ3c=
  on:
    tags: true
