language: python
python:
- '3.8'
install:
- pip install .
script: python3 greedyFAS/calcFAS.py -h
deploy:
  provider: pypi
  username: __token__
  password:
    secure: GOCsVqn6fVxhqF1K+q6yCX6v+xm3YtrVX7Jhalh7wXNJgw4cXulzq4NqKy3Om6h+iphYK7k7UTwXfM+KqM5MI2tsVesM+Mt96JWGT2gWGFJZGgl19hrd356Kb1Ay+4dXRydWSruTSqXS6dgBbhoYnLzgQrjFZXmNnw+NqtMo0XO7U4Pm8NoOzOSPvP8tqcv61QRZ/gxWWVBlitZ0GF527HSAxIpcoUSPl19mEyH5pWxvfrwF2ydAGmdyWzUOaqzD01rYTcLMfOIMqscJ1ui8nVTNHpk3MozU58yVTV7Wa3VapKDXYzGMt+5tZ5aXc/3dczQBv5R4cMx9bCHLXWuIOQjAqON4mtRYKQoRIEFed79Q01UfDF0qEpRWhbye/BvK2WDiwTRUcJdRWDb8Cp/iyDXvXGLCIbujwTptB1+ozvrg0qZvSL0H3aN5WROCczuAiPcimgrEo1UJ8BRfLrukEkV0QKOqUoPsmwEk2sysPwSR8rXerQ5Q8uVvmIXs8pBrrtMDhPpujjR/ZK79h4WUexkDtsUcBi4gdZPy16vguKeughh+qdxQot0EEjHHAEFp7m788zPHZDuJ6fcmKRHZ6uZZWENYVMrUPPXJfMnqzjq/XJMiMQmiQW3Ct+uh8njFjITszB4n2tw8I6oRjHEGtyF6jiJAyG9oLRocSuj0f48=
  on:
    tags: true
