package:
  name: "greedyfas"
  version: "1.7"

requirements:
  build:
    - python
    - setuptools

  run:
    - python


about:
  home: https://github.com/BIONF/FAS
  license: GPL
  summary: tool for protein feature architecture comparisons