{% set name = "FAS" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ./bin/


build:
  noarch: python
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  commands:
    - greedyFAS -h 2>&1
    - parseInterPro -h 2>&1

about:
  home: 'https://github.com/BIONF/FAS'
  license: GPL
  summary: "Tool for protein feature architecture comparisons"